# Generated by Django 3.1.5 on 2021-03-02 20:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210113_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordprofile',
            old_name='house_name',
            new_name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='street_address',
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='default_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='default_street_address1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='default_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='default_town_or_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
