# Generated by Django 3.1.5 on 2021-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
