# Generated by Django 3.1.5 on 2021-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_services_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price_variation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
