# Generated by Django 3.1.5 on 2021-01-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_price_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='one_time_fee',
            new_name='one_time_fee_display',
        ),
    ]
