# Generated by Django 3.1.5 on 2021-03-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20210215_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='bedrooms_dependent',
        ),
        migrations.RemoveField(
            model_name='services',
            name='one_time_fee_display',
        ),
    ]
