# Generated by Django 3.1.5 on 2021-03-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_services_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.main_category'),
        ),
    ]
