# Generated by Django 3.1.5 on 2021-03-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210323_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='main_category',
        ),
    ]
