# Generated by Django 3.1.5 on 2021-03-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_remove_services_main_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_Category',
        ),
    ]
