# Generated by Django 3.1.5 on 2021-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210225_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total_for_anonym',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
