# Generated by Django 3.1.5 on 2021-02-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_grand_total_for_anonym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitemanonym',
            old_name='lineitem_anonym',
            new_name='lineitem_total',
        ),
    ]
