# Generated by Django 3.1.5 on 2021-03-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210228_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total_for_anonym',
        ),
    ]
