# Generated by Django 3.1.5 on 2021-01-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20210113_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=20)),
                ('house_name', models.CharField(blank=True, max_length=20, null=True)),
                ('post_code', models.CharField(max_length=9)),
                ('no_of_bedrooms', models.DecimalField(decimal_places=0, max_digits=2)),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='profiles.landlordprofile')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
