# Generated by Django 3.1.5 on 2021-01-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
