# Generated by Django 3.1.5 on 2021-03-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210215_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
