# Generated by Django 3.1.5 on 2021-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_properties_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
