# Generated by Django 3.1.5 on 2021-03-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210305_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='no_of_bedrooms',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
