# Generated by Django 3.1.5 on 2021-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20210323_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
