# Generated by Django 3.1.5 on 2021-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20210328_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='activate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
