# Generated by Django 3.1.5 on 2021-03-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210328_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
