# Generated by Django 3.1.5 on 2021-04-04 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20210329_2009'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='properties',
            constraint=models.CheckConstraint(check=models.Q(no_of_bedrooms__gt=Decimal('1')), name='no_of_bedrooms_gt_1'),
        ),
    ]
