# Generated by Django 3.1.5 on 2021-04-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20210404_2046'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='properties',
            name='no_of_bedrooms_gt_1',
        ),
    ]
